### ISSUE TITLE
Documentation improvement for newcomers

### ISSUE THREAD

**Issue by aolle** [brainupdaters/drlm-docs#1]
Hi,

please, greater details about installation from source (zip file not working), and deb packaging. 

Add build dependences for the different installation ways (debian: build-essential, git, debhelper, etc.).

A list of Debian supported versions.

A mid-depth technical introduction section will be greatly appreciated.

Thank you.

**Comment by proura** [comment]
Hi @aolle,

We have impoved our documetation following your poposals. Now you can also download the deb package directly from the website of the project http://drlm.org/download/ .

In the coming days we will improve the documentation and adding new sections. It would be helpful to have your feedback again.

Thank you very much,

**Comment by aolle** [comment]
Nice improvement. I installed successfully DRLM on Debian 7.9 release.

We found forgotten double quotes on TFTP configuration causing that the service does not start.

TFTP_DIRECTORY.

Thank you.

**Comment by didacog** [comment]
@aolle Thanks for the feedback!

The double quotes on TFTP_DIRECTORY value are present now. https://github.com/brainupdaters/drlm-docs/commit/b29d134df8d17058a22adc802f093d99124c90be

Regarding the issue, I understand is ready for closing, as the documentation is improved and you installed  successfully DRLM following the manual this time.

Regards,
