### ISSUE TITLE
Doc Improvement

### ISSUE THREAD

**Issue by aolle** [brainupdaters/drlm-docs#3]
Hi All,

following some possible improvement aspects:
- Privileges indicator in ClientConfig and Install docs.
- Replace U+201D with U+0022 (you can omit this if you really need this mark type, but I think that you'll need both U+201C and U+201D in instead of a pair of U+201D).
- Some ReaR arch link provide and rpm on the fly installation. 
- The documentation says that's for CentOS/RHEL6 but you're providing a ReaR package for CentOS/RHEL7.
- Can you provide the links to opensuse that appears in ReaR official site?

Thank you.

**Comment by proura** [comment]
Hi @aolle,

Good improvements! I am agree with all of them and i will try to do it as soon as possible.

Thanks!

**Comment by proura** [comment]
Hello @aolle,

We have added links to ReaR Download Page and OpenSuse, replaced all U+201D with U+0022, changed to CentOS/RHEL6 ReaR version package. 

About the privileges indicator in ClientConfig and Install docs we can't use "#" inside a code box because is detected like a comment. 

Thanks,
